### ISSUE TITLE
http: panic serving [::1]:62459: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by David-kalala** [David-kalala/HFGo#1]
#### What version of Go are you using (go version)?

go version go1.18 windows/amd64

#### Does this issue reproduce with the latest release?
Yes.
#### What did you do?
I run the main.go 
by following this video : [https://www.youtube.com/watch?v=U5OQTd9zerU&list=PLidHThAppdAH4y0DeEf-dGjB-xITVKszL&index=16](url)

#### What did you expect to see?
I expect to see a webb page in the localhost:555

#### What did you see instead?
Server is launched...2022/04/02 21:03:05 http: panic serving 127.0.0.1:59743: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1825 +0xbf
panic({0x7bd000, 0xa490d0})
        C:/Program Files/Go/src/runtime/panic.go:844 +0x258
text/template.(*Template).Lookup(0x0?, {0x800095?, 0xc000071980?})
        C:/Program Files/Go/src/text/template/template.go:189 +0x37
text/template.(*Template).ExecuteTemplate(0x0, {0x88bf40, 0xc00014c0e0}, {0x800095, 0x4}, {0x7d6b60, 0xc000010678})
        C:/Program Files/Go/src/text/template/exec.go:183 +0x4c
main.main.func1({0x88dbf0?, 0xc00014c0e0}, 0x0?)
        C:/Users/canad/go/HeadFirstGo/Jeu/main.go:37 +0x114
net/http.HandlerFunc.ServeHTTP(0x22982e44e00?, {0x88dbf0?, 0xc00014c0e0?}, 0x4ed805?)
        C:/Program Files/Go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x88dbf0, 0xc00014c0e0}, 0xc00014a000)
        C:/Program Files/Go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000078fc0?}, {0x88dbf0, 0xc00014c0e0}, 0xc00014a000)
        C:/Program Files/Go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000ba000, {0x88ddf8, 0xc000086570})
        C:/Program Files/Go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        C:/Program Files/Go/src/net/http/server.go:3071 +0x4db

**Comment by David-kalala** [comment]
`
package main

import (
	// ici on importe des package qu'on va utiliser

	"fmt"
	"math/rand"
	"net/http"
	"os"
	"text/template"
	"time"
)

func main() {

	p, _ := template.ParseGlob("*.html")

	type theGame struct {
		Answer   int
		Attempts int
		Random   int
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		var nombre int
		var essaie = 10

		x := time.Now().Unix()
		rand.Seed(x)
		nbAleatoire := rand.Intn(101) + 1

		data := theGame{nombre, essaie, nbAleatoire}

		p.ExecuteTemplate(w, "game", data)

	})
	folder, _ := os.Getwd()
	fileServer := http.FileServer(http.Dir(folder + "/Jeu"))
	http.Handle("/static/", fileServer)
	fmt.Println(folder)
	fmt.Print("Server is launched...")
	http.ListenAndServe("localhost:555", nil)
}
`

**Comment by David-kalala** [comment]
`{{define "game"}}
<!DOCTYPE html>
<html>

<head>
    <title>
        GuessMe
    </title>
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>
    <h1 style="color: blueviolet; margin-left:40%;">GuessMe</h1>
    <h2 style="color: black;">I've chosen a random number between 1 and 100. Can you guess it ?</h3>
        <h3 style="color: red;"> You have {{.Attempts}} Attempts</h3>
        <form action="/" method="POST" id="myForm">

            {{ if not .Answer}}
            <label for="answer">Make a guess :</label>
            <input type="submit" value="guess">
            <input type="text" name="answer" placeholder="write a number here">
            {{if lt .Answer 0 }}
            <label for="answer">I didn't pick a number below 0. Try again !</label>
            {{if gt .Answer 100 }}
            <label for="answer">I didn't pick a number above 100. Try again !</label>
            {{end}}
        </form>
</body>

</html>
{{ end }}`
